### ISSUE TITLE
Default channel documentation should state that one can specify no channel provisioners

### ISSUE THREAD

**Issue by abbi-gaurav** [knative/docs#1029]
**Describe the change you'd like to see**
There can be scenarios when one does not want to specify a `default-channel-config` and to not use an in-memory-provisioner.
In such a case, a custom provisioner will be installed after installing `knative eventing`.

However, the `knative eventing` fails if one does not provide a `default-channel-config` config map.
Since providing a config map is mandatory, it should be documented with an example that one can specify empty data to have no default channel provisioner configured.

e.g.

```yaml
---
apiVersion: v1
data:
  default-channel-config: ""
kind: ConfigMap
metadata:
  name: default-channel-webhook
  namespace: knative-eventing
```

**Additional context**
