### ISSUE TITLE
Knative Serving: URLs in TrafficTargets in 0.5

### ISSUE THREAD

**Issue by dgerd** [knative/docs#1078]
## What is changing? (Please include as many details as possible.)
The `traffic` block in Service and Route status will have a new field called `url`. For traffic targets that contain a `name` the `url` will display the full endpoint (including scheme) at which the target can be hit.

Example:
```
....
status:
  traffic:
  - name: current
    percent: 100
    revisionName: url-test-g4k56
    url: http://current.url-test.default.example.com
  - name: latest
    percent: 0
    revisionName: url-test-g4k56
    url: http://latest.url-test.default.example.com
```

## How will this impact our users?
Instead of forming the URL based on a well known pattern (i.e. `http://${name}.${status.domain}`) the URL can and should be grabbed from the API.

## In what release will this take happen (to the best of your knowledge)?
Serving 0.5

## Context
Link to associated PRs or issues from other repos here.

1. PR - https://github.com/knative/serving/pull/3526
1. Issue - https://github.com/knative/serving/issues/3450
1. Story (Larger goal of this change) - https://github.com/knative/serving/issues/3419
