### ISSUE TITLE
"Setting up a Custom Domain" example differs from what I got after a fresh install

### ISSUE THREAD

**Issue by steren** [knative/docs#119]
```
apiVersion: v1
data:
  # These are example settings of domain.
  # example.org will be used for routes having app=prod.
  example.org: |
    selector:
      app: prod

  # Default value for domain, for routes that does not have app=prod labels.
  # Although it will match all routes, it is the least-specific rule so it
  # will only be used if no other domain matches.
  example.com: ""
kind: ConfigMap
[...]
```

is not what I got, I got:
```
apiVersion: v1
data:
  example.com: ""
kind: ConfigMap
[...]
```
