### ISSUE TITLE
Hello World - Go(docs/serving/samples/hello-world/helloworld-go/_index.md)

### ISSUE THREAD

**Issue by shenkejie15** [knative/docs#1372]
Your code service.yaml in [tutorial](https://knative.dev/docs/serving/samples/hello-world/helloworld-go/index.html) is wrong. That is more like a yaml for deploying kubernetes service rather than knative service.

**Comment by sebgoa** [comment]
@shenkejie15 can you explain what is wrong in a bit more details. Everything seems fine to me except rendering issue.

The `service.yaml` is a valid knative service manifest and the `helloworld.go` is a Go code:
https://github.com/knative/docs/blob/master/docs/serving/samples/hello-world/helloworld-go/helloworld.go

This is correct.

Let us know what you think is wrong and we can correct it.

**Comment by shenkejie15** [comment]
My apology for being careless.

I got
`Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"`
when I followed the [tutorial](https://knative.dev/docs/serving/samples/hello-world/helloworld-go/index.html). Then I found there was some changes in the service.yaml because the old one was 
   ```
apiVersion: serving.knative.dev/v1alpha1
   kind: Service
   metadata:
     name: helloworld-go
     namespace: default
   spec:
     runLatest:
       configuration:
         revisionTemplate:
           spec:
             container:
               image: docker.io/{username}/helloworld-go
               env:
                 - name: TARGET
                   value: "Go Sample v1"
```

I apply the service successfully with the old yaml file ( In fact I get RevisionMissing but I wasn't aware of that).  So I laid the blame on the service.yaml 

Now I think there is something wrong with my docker or microk8s. All my pods including Knative ones are running. Appreciation for your reply, any more suggestion is welcomed.
