### ISSUE TITLE
serving: No samples for configuring CPU/memory

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1385]
/area serving
/kind bug

I just grepped `cpu:` and `memory:` and it doesn't seem like there are any Knative docs/samples in this repo currently demonstrating how to configure CPU/memory limits/requests.

No need to explain this from scratch (k8s.io has great docs on how limits/request work) but it would be great to show where in the YAML spec to configure it. 

This came as a question on SO: https://stackoverflow.com/questions/56351725/cloud-run-memory-restriction

**Comment by abrennan89** [comment]
@ahmetb just wondering if this issue is still relevant? Was there some particular information you would like to see in the docs?

**Comment by ahmetb** [comment]
Very much relevant. I don’t see a reason why it wouldn’t be.

**Comment by abrennan89** [comment]
> Very much relevant. I don’t see a reason why it wouldn’t be. Overall this is a “task” users should be doing, but no examples exist in docs.

Cool, was just checking since the issue is a year old :slightly_smiling_face:

**Comment by abrennan89** [comment]
@ahmetb this seems to be covered in the latest version of the docs now: https://knative.dev/docs/install/operator/configuring-serving-cr/#system-resource-settings

**Comment by ahmetb** [comment]
@abrennan89 sadly no. Those settings seem to be for the Knative operator itself and not the workloads run by Knative such as KService.

**Comment by evankanderson** [comment]
Hi, this would look like https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spring/index.html with the following YAML:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java-spring
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-java-spring
          resources:
            requests:
              cpu: 100m  # Request 1/10th of a CPU
              memory: 640M  # Enough for anyone
            limits:
              cpu: 1  # Don't allow to use more than 1 core
          env:
            - name: TARGET
              value: "Java Spring Sample v1"
```
