### ISSUE TITLE
event-display service in eventing/samples/github-source doesn't work now

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/docs#1448]
## Expected Behavior

The service display yaml file should be:
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-display
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/knative/eventing-contrib/cmd/event_display
```

## Actual Behavior

When I apply `kubectl apply -f service.yaml`, it reports:
```
$ kubectl --namespace default apply --filename service.yaml
Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"
```
So below yaml file doesn't work.
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: github-message-dumper
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display
```

## Steps to Reproduce the Problem

1. Run command: `kubectl --namespace default apply --filename service.yaml` under the github-source folder.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): IKS
 - Knative Version: 0.6.0
