### ISSUE TITLE
blue/green deployment tutorial should use new v1beta1 API shape

### ISSUE THREAD

**Issue by steren** [knative/docs#1489]
Knative version 0.6+
https://knative.dev/docs/serving/samples/blue-green-deployment/

Doing blue green deployment is done via:
- Using *one* Service object.
- Controlling the revision names
- Updating the traffic section with the revision names and percentages

**Comment by steren** [comment]
CC @mchmarny

**Comment by samodell** [comment]
I think this was (partially?) addressed by #1493

**Comment by steren** [comment]
No, https://github.com/knative/docs/blob/master/docs/serving/samples/blue-green-deployment.md is not up to date with how to simply do blue/green with the v1beta1 API.

Blue/green deployment is as easy as:

````
apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: demo
spec:
  template:
    metadata:
      name: demo-blue
    spec:
      containers:
      - image: mattmoor/ksvc:new

  traffic:
  - revisionName: demo-green
    percent: 75
    name: green

  - revisionName: demo-blue
    percent: 25
    name: blue
```
