### ISSUE TITLE
Improved Knative Serving API Reference

### ISSUE THREAD

**Issue by dgerd** [knative/docs#1796]
**Describe the change you'd like to see**

The current API reference appears to be broken. The format of the previous API reference is difficult to consume. See https://knative.dev/v0.7-docs/reference/serving-api/

Many users are used to the YAML format that they use with kubectl which is hard to construct when reading through from the link above.

YAML Example:
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-test-image
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: knative.dev/serving/test/test_images/helloworld
```
