### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by mjschmidt** [knative/docs#2010]
## Expected Behavior

This example actually went well once I figured out what the docs issue was
This is the page that needs fixing:
https://knative.dev/docs/eventing/samples/kubernetes-event-source/

I expected this command to give me back the pod logs (as described)
kubectl logs -l serving.knative.dev/service=event-display -c user-container

## Actual Behavior

After doing a pod get -o yaml, I realized the pod doesn't actually have that label on it. When I logs the specific pod, I got the expected output. Which is good.

## Steps to Reproduce the Problem

1. Run through the example normally, realize the pod label is no longer on that yaml.
2. I did use docs/0.10 branch. But I doubt that had much to do with it and the docs need to be updated to reflect the 0.10 version push out anyway.

## Additional Info

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.42.2.176/32
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2019-11-30T16:46:19Z"
  generateName: apiserversource-testevents-02c44daf-755b-419e-98b5-b2a077414f14-54b6f8c654-
  labels:
    eventing.knative.dev/source: apiserver-source-controller
    eventing.knative.dev/sourceName: testevents
    pod-template-hash: 54b6f8c654
  name: apiserversource-testevents-02c44daf-755b-419e-98b5-b2a07742nvqs
  namespace: default
  ownerReferences:
...
```
