### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by pablobastidasv** [knative/docs#2061]
## Expected Behavior

When following the examples from [camel source page](https://knative.dev/docs/eventing/samples/apache-camel-source/) in a completely new k8s minikube environment, they work as the page says.

## Actual Behavior

Executing the example `Run a Timer CamelSource` in Minikube (knative with gloo) does not work and I cannot find any documentation that helps me to find what is happening.

Once finished that example, I expect a new pod created (due to knative serving) and this should be logging the event generated by the camel source.

When I check, the channel is ready, but the camel source does not have any event nor info in READY column.

## Steps to Reproduce the Problem

1. `minikube delete`
2. `minikube start --memory=8192 --cpus=6 \
  --vm-driver=hyperkit \
  --disk-size=30g \
  --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"`
3. `kubectl create ns gloo-system`
4. `glooctl install knative -e -k`
5. `minikube addons enable registry`
6. `kamel install`
7. `kubectl apply -f camel.yaml`
8. `kubectl apply -f display_resource.yaml`
9. `kubectl apply -f source_timer.yaml`

### Versions

minikube: v1.6.1
k8s: Client v1.17.0, Server v1.17.0
gloo: Client 1.2.1, Server 1.2.1
kamel: 1.0.0-M4

### camel.yaml

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: knative-sources

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller-manager
  namespace: knative-sources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources/status
  - camelsources/finalizers
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - camel.apache.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    duck.knative.dev/source: "true"
    eventing.knative.dev/release: devel
  name: eventing-contrib-camel-source-observer
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: camel-controller
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: eventing-sources-camel-controller-addressable-resolver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    duck.knative.dev/source: "true"
  name: camel-source-observer
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    duck.knative.dev/source: "true"
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: camelsources.sources.eventing.knative.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: CamelSource
    plural: camelsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            ceOverrides:
              description: Defines overrides to control modifications of the event
                sent to the sink.
              type: object
            sink:
              description: Reference to an object that will resolve to a domain name
                to use as the sink.
              type: object
            source:
              properties:
                flow:
                  type: object
                integration:
                  type: object
              type: object
          required:
          - source
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
          type: object
  version: v1alpha1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  ports:
  - name: https-camel
    port: 443
  selector:
    control-plane: camel-controller-manager

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  selector:
    matchLabels:
      control-plane: camel-controller-manager
  serviceName: camel-controller-manager
  template:
    metadata:
      labels:
        control-plane: camel-controller-manager
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/camel/source/cmd/controller@sha256:b2907d7366cda7cd3a738df344d941997a7246cc2809cf6f1115dea361b070ce
        name: manager
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: camel-controller-manager
      terminationGracePeriodSeconds: 10

---

```

### display_resource.yaml

```yaml
# Channel for testing events.

apiVersion: messaging.knative.dev/v1alpha1
kind: InMemoryChannel
metadata:
  name: camel-test

---

# Subscription from the CamelSource's output Channel to the Knative Service below.

apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: camel-source-display
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: camel-test
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: camel-event-display

---

# This is a very simple Knative Service that prints the input event to its log.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: camel-event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:f4628e97a836c77ed38bd3b6fd3d0b06de4d5e7db6704772fe674d48b20bd477


```

### source_timer.yaml

```yaml
# Apache Camel Timer Source
#
# Timer Component documentation: https://camel.apache.org/components/latest/timer-component.html
#
# List of available Apache Camel components: https://camel.apache.org/components/latest/
#
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-timer-source
spec:
  source:
    flow:
      from:
        uri: timer:tick
        parameters:
          period: 2s
        steps:
          - set-header:
              name: Content-Type
              constant: text/plain
          - set-body:
              constant: Hello world!
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: InMemoryChannel
      name: camel-test


```
