### ISSUE TITLE
source to url doc has auth failure

### ISSUE THREAD

**Issue by krancour** [knative/docs#207]
Following [these directions](https://github.com/knative/docs/blob/master/serving/samples/source-to-url-go/README.md) to the letter, the Kaniko build appears to fail on push:

```
...
2018/07/19 20:39:34 No matching credentials found for index.docker.io, falling back on anonymous
time="2018-07-19T20:39:34Z" level=error msg="UNAUTHORIZED: \"authentication required\""
```

Secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  username: a3JhbmNvdXI=
  password: <redacted>
```

Service:

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/mchmarny/simple-app.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: &image docker.io/krancour/app-from-source:latest
      revisionTemplate:
        spec:
          container:
            image: *image
            imagePullPolicy: Always
            env:
            - name: SIMPLE_MSG
              value: "Hello sample app!"

```
