### ISSUE TITLE
Wrong fields in eventing/samples/kafka/source/event-display.yaml

### ISSUE THREAD

**Issue by enricofranco** [knative/docs#2071]
File `docs/eventing/samples/kafka/source/event-display.yaml` reports

```yaml
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ...
```

Applying this yaml, console returns this message:

```console
admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "runLatest"
```

Modifying the yaml file in this way, according to this page https://github.com/knative/docs/blob/master/docs/serving/spec/knative-api-specification-1.0.md#service-2, it is correctly applied.

```yaml
  template:
    spec:
      containers:
        - image: ...
```

Are there any mismatches in the docs?
