### ISSUE TITLE
Container Source Example(docs/eventing/samples/container-source/index.md)

### ISSUE THREAD

**Issue by astoycos** [knative/docs#2179]
## Expected Behavior
Expected Container Source Example to work correctly 

## Actual Behavior
Error is reported, Event-Display service shows the following error

End Log looks like the following 
`{"level":"error","ts":1581004429.103795,"logger":"fallback","caller":"http/transport.go:408","msg":"failed to decode message","error":"unknown encoding","stacktrace":"github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/go/src/github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:408\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2375\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878"}
`

Heartbeats Container source error looked like the following 
`2020/02/06 16:02:49 failed to send cloudevent: error sending cloudevent: 400 Bad Request`
 
## Steps to Reproduce the Problem

1.Follow the Container Source Example [Docs](https://knative.dev/docs/eventing/samples/container-source/)
1.
1.

## Additional Info
**Additional context**

Just change the Service Yaml Container Image path to fix, should look like this

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
```

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by vishaltak** [comment]
Looks like the latest version of "event_display" throws these errors. Don't know if this is by design or a compatibility issue.

@astoycos - If you update your image digest as follows, things should work fine.

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
```
