### ISSUE TITLE
Document Broker.spec.config usage.

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#2227]
## What is changing? (Please include as many details as possible.)

In v1beta1 `Broker.spec.config` is now used instead of `Broker.spec.channeTemplateSpec`

Config is a pointer to anything, but in the impl of Channel based Broker, it will be a configmap with the following shape:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
data:
  channelTemplateSpec.apiVersion: ChannelApiVersion
  channelTemplateSpec.kind: ChannelKind
  channelTemplateSpec.specJson: <json of a spec if needed>
```

## How will this impact our users?
The broker will work with either `spec.channelTempalteSpec` or the new shape `spec.config` in v1alpha1.

## In what release will this take happen (to the best of your knowledge)?

0.13

@n3wscott to follow up and document this.

**Comment by n3wscott** [comment]
Implemented here: https://github.com/knative/eventing/pull/2596

**Comment by matzew** [comment]
@n3wscott what's not really clear to me is:

using the `default` broker... and doing the labeling (`kubectl label namespace default knative-eventing-injection=enabled`)  - how can I than set the `.config` to point to a `KafkaChannel` configuration ?   Or is that now impossible?

**Comment by matzew** [comment]
Ah, it will than still go via the `default-ch-config` CM ...  

ok

**Comment by matzew** [comment]
One more,  @n3wscott 

for `Broker.spec.config`  do I list the name of the config map ? 

I am not sure I understand this vague text:

> Config is a pointer to anything

**Comment by matzew** [comment]
ah, like

```
apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: default
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-broker
```
