### ISSUE TITLE
Document how to change the broker defaults

### ISSUE THREAD

**Issue by matzew** [knative/docs#2371]
Document how to change the default broker from `channel-broker` to `mt-channel-broker`.

By changing the configmap to:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  # Configuration for defaulting channels that do not specify CRD implementations.
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-br-default-channel
      namespace: knative-eventing
```
