### ISSUE TITLE
documentation has invalid config map

### ISSUE THREAD

**Issue by vagababov** [knative/docs#2565]
@nicks reports:

/area API
/kind doc

## Expected Behavior

This doc
https://knative.dev/docs/serving/tag-resolution/

has this ConfigMap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: knative-serving

data:
  # List of repositories for which tag to digest resolving should be skipped
  registriesSkippingTagResolving: registry.example.com
```

When I apply this config map to my cluster, I get this error:

```
admission webhook "config.webhook.serving.knative.dev" denied the request: validation failed: queueSidecarImage cannot be empty or unset
: exit status 1
```

## Actual Behavior
I would expect examples on the knative documentation site to work out of the box
