### ISSUE TITLE
Broker example using config-br-defaults appears wrong.

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2753]
## Expected Behavior
https://github.com/knative/docs/tree/master/docs/eventing/broker

The example says this will use `config-br-defaults` but the spec and annotations are filled in and hence it does not use the defaults from the configmap. It's a fully specified broker.

```
kubectl create -f - <<EOF
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: default
  namespace: default
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
EOF
```

## Actual Behavior

```
kubectl create -f - <<EOF
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: default
EOF
```
Which will then use config-br-defaults to fill in proper values.
@abrennan89 

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version: HEAD
