### ISSUE TITLE
Unsure where to add timeoutSeconds for "serving"

### ISSUE THREAD

**Issue by alexellis** [knative/docs#281]
## Expected Behavior

I'm unsure where to add timeoutSeconds for "serving". Would be good to have a clear way to define a timeout value for a service. This is the first thing we found people wanted with functions when building OpenFaaS.

## Actual Behavior

Tried to follow docs, every position in the YAML ends up producing an error. Perhaps an example/sample could be given?

## Steps to Reproduce the Problem

I've tried adding `timeoutSeconds: 60` in just about everywhere I could fit it - reference - https://github.com/knative/serving/blob/master/docs/spec/spec.md#configuration

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: inception-openfaas
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: alexellis/inception:2.1
            env:
            - name: fprocess
              value: "python3 index.py"
            - name: read_timeout
              value: "60s"
            - name: write_timeout
              value: "60s"
```

**Comment by alexellis** [comment]
@mchmarny ptal? This issue has been unanswered for around 2 weeks now.

**Comment by mattmoor** [comment]
Here's the original issue mentioning the timeout field: https://github.com/knative/serving/issues/457

Per the spec it would be something like:
```yaml
...
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          timeoutSeconds: 60
          container:
            image: alexellis/inception:2.1
```

However, I think it's blocked on Istio functionality: https://github.com/knative/serving/issues/487

/unassign @evankanderson @mattmoor
/assign @tcnghia
