### ISSUE TITLE
eventing config-br-defaults set delivery spec defaults

### ISSUE THREAD

**Issue by runzexia** [knative/docs#2944]
**Describe the change you'd like to see**
add docs about how to set delivery spec defaults by changing config-br-defaults

**Additional context**
https://github.com/knative/eventing/issues/4172
https://github.com/knative/eventing/pull/4328

**Comment by xtreme-sameer-vohra** [comment]
Would it be possible to automate this based on the the schema, like this [tool](https://github.com/alecthomas/jsonschema) allows ?

**Comment by abrennan89** [comment]
Requires updates to the docs here: https://dev-knative.netlify.app/development/admin/eventing/broker-configuration/

**Comment by pierDipi** [comment]
I'm adding more details to this issue.

On this page https://knative.dev/docs/eventing/configuration/broker-configuration/
users can configure some Broker defaults cluster-wide or per namespace.
For example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: devel
data:
  # Configures the default for any Broker that does not specify a spec.config or Broker class.
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-kafka-channel
      namespace: knative-eventing
    namespaceDefaults:
      namespace-1:
        apiVersion: v1
        kind: ConfigMap
        name: config-br-default-channel
        namespace: knative-eventing
```

With the new feature, another field called `delivery` can be configured as well, as follows:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: devel
data:
  # Configures the default for any Broker that does not specify a spec.config or Broker class.
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-kafka-channel
      namespace: knative-eventing
      delivery:
        retry: 10
        backoffDelay: PT0.2S
        backoffPolicy: exponential
    namespaceDefaults:
      namespace-1:
        apiVersion: v1
        kind: ConfigMap
        name: config-br-default-channel
        namespace: knative-eventing
        delivery:
          deadLetterSink:
            ref:
              kind: Service
              namespace: example-namespace
              name: example-service
              apiVersion: v1
            uri: example-uri
          retry: 10
          backoffPolicy: exponential
          backoffDelay: "PT0.2S" 
```

The `delivery` field has the same shape as the delivery field of the broker as shown on this page https://knative.dev/docs/eventing/broker/example-mtbroker/:

```yaml
# ...
 spec:
   # ...
   delivery:
     deadLetterSink:
       ref:
         kind: Service
         namespace: example-namespace
         name: example-service
         apiVersion: v1
       uri: example-uri
     retry: 10
     backoffPolicy: exponential
     backoffDelay: "PT0.2S"
```
