### ISSUE TITLE
Install Future Serving via Operator is broken

### ISSUE THREAD

**Issue by matzew** [knative/docs#3186]
Following the doc guide:

> The field `spec.version` is used to set the version of Knative Serving. Replace` {{spec.version}}` with the correct version number.

and doing something like:

```
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.20.0
  manifests:
    - URL: https://github.com/knative/serving/releases/download/v${VERSION}/serving-core.yaml
    - URL: https://github.com/knative/serving/releases/download/v${VERSION}/serving-hpa.yaml
    - URL: https://github.com/knative/serving/releases/download/v${VERSION}/serving-post-install-jobs.yaml
    - URL: https://github.com/knative/net-istio/releases/download/v0.17.0/net-istio.yaml

```

Fails, giving me this log:

```
{"severity":"ERROR","timestamp":"2021-01-25T11:37:31.101667592Z","logger":"knative-operator","caller":"controller/controller.go:540","message":"Reconcile error","knative.dev/pod":"knative-operator-775865b79d-dtwnp","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","duration":0.009135649,"error":"The version of the manifests v0.17.0 does not match the target version of the operator CR v0.20.0. The resource name is knative-serving-istio.","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210118192521-75d66b58948d/controller/controller.go","line":"540","function":"knative.dev/pkg/controller.(*Impl).handleErr"},"stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210118192521-75d66b58948d/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210118192521-75d66b58948d/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210118192521-75d66b58948d/controller/controller.go:460"}

```

The istio version should be also `v${VERSION}` ...
