### ISSUE TITLE
Sink binding(docs/eventing/sources/sinkbinding.md)

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3218]
As follows `ref:` should indent two spaces
![image](https://user-images.githubusercontent.com/17523539/107139693-2d1f5a00-6958-11eb-8df6-a5eea23e2446.png)

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-heartbeat
spec:
  subject:
    apiVersion: batch/v1
    kind: Job
    selector:
      matchLabels:
        app: heartbeat-cron
    sink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
```
