### ISSUE TITLE
Simplify Installing Istio for Knative (docs/install/installing-istio.md)

### ISSUE THREAD

**Issue by howardjohn** [knative/docs#3442]
## Expected Behavior
Installation is as simple as possible

## Actual Behavior

Install has a few redundant steps, and some that do nothing

```
cat << EOF > ./istio-minimal-operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
EOF

istioctl install -f istio-minimal-operator.yaml
```

^ is 100% equivalent to what is offered and a bit simpler.

I would further recommend removing the autoInject=disabled and jwtPolicy.

Istio injection is already opt in by namespace label, so I think it adds complexity to explicitly disable it. Additionally, autoInject=disabled does *not* disable the mutating webhook that injects pods, so its not actually a great way to disable it as pods still have a hard dependency on istiod to startup.

`jwtPolicy: first-party-jwt` - this is not going to work in Kubernetes 1.21+. See https://github.com/istio/istio/issues/31964. Maybe we need to add some extra steps to make it backwards compatible, but it will be at the cost of some questionable security practices. first-party-jwt is _highly_ discouraged.
