### ISSUE TITLE
Describe SASL option for KafkaSource

### ISSUE THREAD

**Issue by matzew** [knative/docs#3583]
**Describe the change you'd like to see**

I do not see any SASL related documentation in the kafka source docs: 
https://knative.dev/development/developer/eventing/sources/kafka-source/

However, the Source does support SASL in various ways, and it should be documented.

Some comments on the relevant bits are in here:
https://github.com/knative-sandbox/eventing-kafka/pull/237#issuecomment-734721870

Ideally we have some doc that describe the following section, for SASL:
```
...
net:
  sasl:
   enable: true
   user:
      secretKeyRef:
        name: strimzi-sasl-secret
        key: user
    password:
      secretKeyRef:
        name: strimzi-sasl-secret
        key: password
    saslType:
      secretKeyRef:
        name: strimzi-sasl-secret
        key: saslType
...
```
