### ISSUE TITLE
Document limitations of redirects in virtual services

### ISSUE THREAD

**Issue by PurpleBooth** [knative/docs#400]
## Expected Behavior

When you issue a 30X redirect is issued by a service behind an entry route, you might expect the response to be rewritten like below (I know I did, perhaps naively).

Assuming a setup like the [knative-routing-go](https://github.com/knative/docs/blob/master/serving/samples/knative-routing-go) example.

```
Request: http://example.com/login/resource -> login-service.default.example.com/resource
Response: 302 login-service.default.example.com/other-resource ->  http://example.com/login/other-page
```

This is less of a problem with Istio alone because you can change the VirtualServer that points to your service directly, and make it work with the host you want, however with Knative you need to route back to `knative-ingressgateway.istio-system.svc.cluster.local`, meaning you have to rewrite `Host: example.com` to `Host: login-service.default.example.com`.

There should be a note about this.

## Actual Behavior

```
Request: http://example.com/login/resource -> login-service.default.example.com/resource
Response: 302 login-service.default.example.com/other-resource ->  http://login-service.default.example.com/other-page
```

And no note about the leaked generic domain.

## Additional Info

**Note:** I don't expect a solution to this problem, just giving context to the above.

My specific problem here is I want a custom domain on a per-service basis, like purplebooth.co.uk and www.purplebooth.co.uk, then to route that internally to the right service.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: purplebooth-co-uk-v2-domain
  labels:
    app: purplebooth-co-uk-v2
spec:
  gateways:
  - knative-shared-gateway.knative-serving.svc.cluster.local
  hosts:
  - purplebooth.co.uk
  - www.purplebooth.co.uk
  http:
  - rewrite:
      authority:  purplebooth-co-uk-v2.default.solace-system.net
    route:
      - destination:
          host: knative-ingressgateway.istio-system.svc.cluster.local
        weight: 100
```

Like in the [knative-routing-go](https://github.com/knative/docs/blob/master/serving/samples/knative-routing-go) example, all be it simpler. I assume this will be a pretty common problem.

I am not worried about rewriting URLs in the page or anything, just handling a specific case with a redirect. I tried something similar to below, however, it has that specific version in the headers, and didn't seem to trigger the scaling up/down process.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    route: purplebooth-co-uk-v2
  name: purplebooth-co-uk-v2
  namespace: default
spec:
  gateways:
  - knative-shared-gateway.knative-serving.svc.cluster.local
  - mesh
  hosts:
  - 'purplebooth.co.uk'
  http:
  - appendHeaders:
      knative-serving-namespace: default
      knative-serving-revision: purplebooth-co-uk-v2-00001
      x-envoy-upstream-rq-timeout-ms: "0"
    match:
    - authority:
        exact: purplebooth-co-uk-v2.default.solace-system.net
    - authority:
        exact: purplebooth-co-uk-v2.default.svc.cluster.local
    route:
    - destination:
        host: activator-service.knative-serving.svc.cluster.local
        port:
          number: 80
      weight: 100
    timeout: 60s
```

Now I can force the redirect to go to the correct URL by manually setting it to a specific URL, but that doesn't feel like a very nice solution, particularly if in the future I want to compose existing customers APIs together.
