### ISSUE TITLE
Change the port of Knative Service

### ISSUE THREAD

**Issue by mukundjalan** [knative/docs#4383]
I have been trying to change the port of the "Service" object created by Knative but I do not see any option in the specifications to do so. 

I am able to change the container port but that is not what I am trying to achieve. I need the service to listen on a different port (9080 in my case) from another service in the cluster or from outside the cluster.

Why is this required:
I am trying to create a POC with Istio & Knative in an EKS cluster owned by me. For this I was trying to convert the sample application "bookinfo" provided by istio from a generic k8s configuration to a knative service configuration. The microservices have a hardcoded 9080 port to communicate amongst each other as [here](https://github.com/istio/istio/blob/master/samples/bookinfo/src/productpage/productpage.py#L67). I was wondering that if we upgrade an existing system, we might have to face similar challenge as we may or may not have the liberty to update ports of the services that we are communicating within.

The original configuration for bookinfo application is available [here](https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml)
The modified k8s configuration of bookinfo application is as below
```yaml
##################################################################################################
# Details service
##################################################################################################
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: details
spec:
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  labels:
    account: details
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ratings
spec:
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reviews
spec:
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
#        volumeMounts:
#        - name: tmp
#          mountPath: /tmp
#        - name: wlp-output
#          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
#      volumes:
#      - name: wlp-output
#        emptyDir: {}
#      - name: tmp
#        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: productpage
spec:
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
#        volumeMounts:
#        - name: tmp
#          mountPath: /tmp
        securityContext:
          runAsUser: 1000
#      volumes:
#      - name: tmp
#        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  labels:
    account: productpage
```
References
- Istio POC: https://www.eksworkshop.com/advanced/310_servicemesh_with_istio/deploy/
- Source Code: https://github.com/istio/istio/tree/master/samples/bookinfo
- https://github.com/istio/istio/blob/master/samples/bookinfo/src/productpage/productpage.py

**Comment by snneji** [comment]
@nak, would you be able to help with this?

**Comment by nak3** [comment]
Hi @mukundjalan

Please allow me to confirm which "Service" pod you would like to change:
For example, when we deployed `hello-example` ksvc, Knative creates the following ksvc and k8s services.

```
$ kubectl get ksvc
NAME            URL                                        LATESTCREATED         LATESTREADY           READY   REASON
hello-example   http://hello-example.default.example.com   hello-example-00001   hello-example-00001   True

$ kubectl get svc
NAME                          TYPE           CLUSTER-IP     EXTERNAL-IP                                            PORT(S)                                      AGE
hello-example                 ExternalName   <none>         knative-local-gateway.istio-system.svc.cluster.local   80/TCP                                       10s
hello-example-00001           ClusterIP      10.96.130.57   <none>                                                 80/TCP                                       59s
hello-example-00001-private   ClusterIP      10.96.101.65   <none>                                                 80/TCP,9090/TCP,9091/TCP,8022/TCP,8012/TCP   59s
```

Could you please point out what port you want to change to?

**Comment by mukundjalan** [comment]
Hi @nak3, 

Here I would like to change the port of "hello-example" service to some value other than 80, lets say 9090. How can I achieve this?

**Comment by ghiander** [comment]
Hello all,

I have come across the same problem. To summarise, I can configure the ksvc to have

```
ports:
    - containerPort: 9000
      name: http1
      protocol: TCP
```

The configured port will be inherited correctly by the children pod

```
ports:
    - containerPort: 9000
      name: user-port
      protocol: TCP
```

But it does not get picked up by the children svc:

```
spec:
  externalName: herg-svc.pip-prod.svc.cluster.local
  ports:
  - appProtocol: kubernetes.io/h2c
    name: http2
    port: 80
    protocol: TCP
    targetPort: 80
```

Is this a bug? There should be a way to configure both port and targetPort of the svc object.
