### ISSUE TITLE
can't create a KafkaSource?

### ISSUE THREAD

**Issue by fengqi2019** [knative/docs#4504]
## Expected Behavior
when i create kafkasource as doc
```
abc@DESKTOP-06B3E7S:~/knative$ kubectl apply -f kafka-source.yaml
kafkasource.sources.knative.dev/kafka-source created
```
i should find kafkasource pod:
```
NAME                                            READY     STATUS    RESTARTS   AGE
event-display-00001-deployment-5d5df6c7-gv2j4   2/2       Running   0          72s
```
## Actual Behavior
but i can't find the pod
```
abc@DESKTOP-06B3E7S:~/knative$ kubectl get pods -A | grep source
abc@DESKTOP-06B3E7S:~/knative$
```
### kafka-source.yaml
```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers:
  - kafka-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - knative-demo-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: kafka
```
### kafka-topic.yaml
```
huangjm@DESKTOP-06B3E7S:~/knative$ kubectl get kafkatopic -A
NAMESPACE   NAME                                                                                               CLUSTER         PARTITIONS   REPLICATION FACTOR   READY
kafka       knative-demo-topic                                                                                 kafka-cluster   3            1                    True
```
yaml:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: knative-demo-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
### service.yaml

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: kafka
#  annotations:
#    autoscaling.knative.dev/minScale: 1
spec:
  template:
    spec:
      containers:
        - # This corresponds to
          # https://github.com/knative/eventing/tree/main/cmd/event_display/main.go
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
```
