### ISSUE TITLE
Eventing Sugar Controller Trigger sugaring expects Broker name to be "default"

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#4543]
## Expected Behavior
Instructions on [Sugar Controller](https://knative.dev/docs/eventing/sugar/) are correct and work

## Actual Behavior
Following the [Sugar Trigger Example](https://knative.dev/docs/eventing/sugar/#trigger-examples) 
```
kubectl apply -f - << EOF
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: hello-sugar
  namespace: hello
  annotations:
    eventing.knative.dev/injection: enabled
spec:
  broker: sugar
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
EOF
```
fails with

```
Error from server (BadRequest): error when creating "some-trigger.yaml": admission webhook "validation.webhook.eventing.knative.dev" denied the request: validation failed: The provided injection annotation is only used for default broker, but non-default broker specified here: "sugar": metadata.annotations[eventing.knative.dev/injection]
```

Update the instructions to mention that Broker's name must be `default` as the [admission webhook expects it](https://github.com/knative/eventing/blob/main/pkg/apis/eventing/v1/trigger_validation.go#L143-L148).

## Steps to Reproduce the Problem
See above

## Additional Info
**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Kind/Local
 - Knative Version: 1.0
