### ISSUE TITLE
Fix example to immediately collect any inactive revision

### ISSUE THREAD

**Issue by amandahla** [knative/docs#4652]
Update docs according to https://github.com/knative/serving/pull/12517

Problem related in https://github.com/knative/serving/issues/12422

## Expected Behavior

Immediately collect any inactive revision
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  namespace: knative-serving
data:
  min-non-active-revisions: "0"
  max-non-active-revisions: "0"
  retain-since-create-time: "disabled"
  retain-since-last-active-time: "disabled"
```

## Actual Behavior

Immediately collect any inactive revision
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  namespace: knative-serving
data:
  min-non-active-revisions: "0"
  retain-since-create-time: "disabled"
  retain-since-last-active-time: "disabled"
```
