### ISSUE TITLE
Improve documentation on configuring the default BrokerClass

### ISSUE THREAD

**Issue by matzew** [knative/docs#4822]
The doc https://knative.dev/docs/eventing/configuration/broker-configuration/#configuring-the-default-brokerclass-for-namespaces

is a little misleading or not fully correct.

* `KafkaBroker` -> there is no such `class`, the Kafka-based broker impl does use `Kafka` instead
* The config just contains the `brokerClass` field, usually each broker has different configuration, captured in a config map. This should be reflected in the doc as well. An example for some better `Kafka` config would go like:
```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  defaultBrokerClass: Kafka
  config:
    config-br-defaults:
      default-br-config: |
        clusterDefault:
          apiVersion: v1
          kind: ConfigMap
          name: kafka-broker-config
          namespace: knative-eventing
```
