### ISSUE TITLE
Hello World - Rust(community/samples/serving/helloworld-rust/index.md)

### ISSUE THREAD

**Issue by dgeorgievski** [knative/docs#4894]
Under step 4. `Create a new file, service.yaml ...` of Rust Serving example
https://knative-v1.netlify.app/community/samples/serving/helloworld-rust/

the following knative service has two syntax indentation errors at containers and env value.
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-rust
  namespace: default
spec:
  template:
    spec:
    containers:
      - image: docker.io/{username}/helloworld-rust
        env:
          - name: TARGET
        value: "Rust Sample v1"
```

The correct format should be
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-rust
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-rust
          env:
            - name: TARGET
              value: "Rust Sample v1"
```
