### ISSUE TITLE
Subscription doc lacks reply channel feature

### ISSUE THREAD

**Issue by matzew** [knative/docs#4937]
The yaml version of a subscription does lack the optional `reply` feature.

The subscription has two `Destination`s, `subscriber` and `reply`:
https://github.com/knative/eventing/blob/main/pkg/apis/messaging/v1/subscription_types.go#L97-L102

The `kn` client doc does have it, but the yaml not.. would be nice if doc would be changed to:

    ```yaml
    apiVersion: messaging.knative.dev/v1
    kind: Subscription
    metadata:
      name: <subscription-name> # Name of the Subscription.
      namespace: default
    spec:
      channel:
        apiVersion: messaging.knative.dev/v1
        kind: Channel
        name: <channel-name> # Configuration settings for the Channel that the Subscription connects to.
      delivery:
        deadLetterSink:
          ref:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: <service-name>
            # Configuration settings for event delivery.
            # This tells the Subscription what happens to events that cannot be delivered to the Subscriber.
            # When this is configured, events that failed to be consumed are sent to the deadLetterSink.
            # The event is dropped, no re-delivery of the event is attempted, and an error is logged in the system.
            # The deadLetterSink value must be a Destination.
      reply:
        ref:
          apiVersion: messaging.knative.dev/v1
          kind: InMemoryChannel
          name: <service-name> # Configuration settings for the reply event. This is the event Sink that events replied from the subscriber are delivered to.
      subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: <service-name> # Configuration settings for the Subscriber. This is the event Sink that events are delivered to from the Channel.
    ```
