### ISSUE TITLE
Using upstash kafka for knative broker bootstrap.server is not work

### ISSUE THREAD

**Issue by Kcwan18** [knative/docs#4949]
## Steps to Reproduce the Problem

1. Install the knative eventing and the kafka controller
```
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.4.0/eventing-core.yaml
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.4.0/eventing-kafka-controller.yaml
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.4.0/eventing-kafka-broker.yaml
```
2. Add a secret file for the upstash kafka certification 
If using the SASL_SSL protocol, what is the pem key file
```
kubectl create secret --namespace knative-eventing  generic kafka-secret \
  --from-literal=protocol=SASL_SSL \
  --from-literal=sasl.mechanism=SCRAM-SHA-256 \
  --from-file=ca.crt=caroot.pem \                                     <-------- ???????????????? 
  --from-literal=user=<my_user> \
  --from-literal=password=<my_password>
 ```
If I skip the line of the ca.crt=xxx.pem, the error message is 
```
failed to create topic: knative-broker-default-default: kafka: error decoding packet: correlation ID didn't match, wanted 3, got 4
```

3. Update the "bootstrap.servers" and "auth.secret.ref.name" in the kafka-broker-config.yaml as below
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
data:
  # Number of topic partitions
  default.topic.partitions: "10"
  # Replication factor of topic messages.
  default.topic.replication.factor: "1"
  # A comma separated list of bootstrap servers. (It can be in or out the k8s cluster)
  bootstrap.servers: "evident-xxxxx-kafka.upstash.io:9092"
  auth.secret.ref.name: kafka-secret
  ```

After doing those step, I describe the broker and it return the message below.
```
Events:
  Type     Reason           Age                 From               Message
  ----     ------           ----                ----               -------
  Normal   FinalizerUpdate  23s                 broker-controller  Updated "default" finalizers
  Warning  InternalError    13s (x12 over 23s)  broker-controller  Data plane not available: Did you install the data plane for this component?
  Warning  InternalError    0s                  broker-controller  failed to create topic: knative-broker-default-default: kafka: error decoding packet: correlation ID didn't match, wanted 3, got 4
```
