### ISSUE TITLE
Eventing PubSub sample ko shouldn't pass namespace

### ISSUE THREAD

**Issue by justingrayston** [knative/docs#529]
## Expected Behavior
On https://github.com/knative/docs/tree/master/eventing/samples/gcp-pubsub-source where you deploy the subscriber you should be able to deploy it

## Actual Behavior
The instructions given state `ko -n default apply -f eventing/samples/gcp-pubsub-source/subscriber.yaml` but ko doesn't take a namespace arg and errors with `Error: unknown shorthand flag: 'n' in -n`

## Steps to Reproduce the Problem

1. Run ko -n default apply -f eventing/samples/gcp-pubsub-source/subscriber.yaml
2. get error
3. 

## Additional Info
I _think_ that without specifying a namespace it would go into default anyway, and the idea is to build the message dumper image with `ko` and the apply the config. If someone can confirm, I will remove and make a pull request. Sadly, if I do remove it I still get an error, but that looks to be an API spec error and should probably be a separate issue. (The error is `Error from server (InternalError): error when creating "STDIN": Internal error occurred: admission webhook "webhook.eventing.knative.dev" denied the request: mutation failed: missing field(s): spec.channel`)

**Comment by justingrayston** [comment]
I see the spec issue should be along these lines as per #519 
```
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: iot-demo
  namespace: default
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: CHANNEL_NAME
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
```
