### ISSUE TITLE
Google Pub/Sub sample could use love

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#548]
https://github.com/knative/docs/tree/master/eventing/samples/gcp-pubsub-source#gcp-cloud-pubsub---source

In particular, why don't we just provide gcloud commands for step `#6` instead of having two sections with 4 sub-steps a piece.

**Comment by mattmoor** [comment]
cc @evankanderson @vaikas-google

**Comment by mattmoor** [comment]
`ko` doesn't support a `-n` option: https://github.com/knative/docs/tree/master/eventing/samples/gcp-pubsub-source#subscriber

**Comment by mattmoor** [comment]
^^ These shouldn't reference `ko` at all, but should at least work.

**Comment by mattmoor** [comment]
There's a number of places I've seen installing the latest nightly (should be 0.2.x)

**Comment by mattmoor** [comment]
[This](https://github.com/knative/docs/blob/master/eventing/samples/gcp-pubsub-source/subscriber.yaml) should use the spec:
```yaml
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: qux-1
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
```
