### ISSUE TITLE
autoscaling metric type - memory, not working (always create cpu metric based hpa) 

### ISSUE THREAD

**Issue by Parneet-Raghuvanshi** [knative/docs#5537]
/area autoscale

I am trying to create **hpa** for memory based **metric**, so I provided the annotations in my service according to docs.
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "memory"
```
https://knative.dev/docs/serving/autoscaling/autoscaling-metrics/#setting-metrics-per-revision

HPA ->
<img width="501" alt="image" src="https://user-images.githubusercontent.com/54593571/233190186-7d0e534f-753a-48d9-bd92-6eae1f81a81c.png">
as you can see, metric type is only CPU, I have also checked yaml output, but it always create a **hpa** with **cpu** metrics only, I don't have much experience with this autoscaling.

And the annotations are added to my hpa from service.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/54593571/233191387-55f02a68-150d-43ab-8adc-d85dd4c4f30f.png">

Any suggestions on this, or what I am doing wrong.
