### ISSUE TITLE
Multiple Istio Gateways - how do I specify which one?

### ISSUE THREAD

**Issue by rblaine95** [knative/docs#5589]
We have multiple Istio Ingress Gateways:
- `istio-internal` for private endpoints (accessible via VPN)
- `istio-external` for publicly accessible endpoints

With an Istio Virtual Service you can choose which gateways route the service:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example
spec:
  gateways:
  - istio-system/istio-external
  - istio-system/istio-internal
```
This Virtual Service will be both public and privately exposed.
With Knative Service, I'm seeing that the Virtual Services being created by it are selecting all configured Gateways:
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-local-gateway:
        selector:
          app: istio-ingressgateway
  config:
    istio:
      gateway.istio-system.istio-internal: istio-internal.istio-system.svc.cluster.local
      gateway.istio-system.istio-external: istio-external.istio-system.svc.cluster.local
    domain:
        example.com: ""
    network:
      domain-template: "{{.Name}}.{{.Domain}}"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: knative-example
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
```
This then results in the following Gateway config in a Virtual Service:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
[...]
  name: hello-ingress
  namespace: knative-example
spec:
  gateways:
  - istio-system/istio-external
  - istio-system/istio-internal
  - knative-serving/knative-local-gateway
[...]
```
Is there a way to choose the gateway that the Knative service is exposed on?
