### ISSUE TITLE
Document progressDeadline annotation on per revision basis

### ISSUE THREAD

**Issue by andrew-delph** [knative/docs#5767]
**Documentation request**

The feature to set progressDeadline on a per-revision basis has been recently introduced. Previously, this setting was only configurable on a global level. However, there appears to be a lack of documentation regarding this new capability.
- https://github.com/knative/serving/issues/12743

Current documentation for global progress deadline can found [here](https://knative.dev/docs/serving/configuration/deployment/#configuring-progress-deadlines).

Possibly documentation can be similar to target RPS: https://knative.dev/docs/serving/autoscaling/rps-target/#configuring-the-requests-per-second-rps-target

here is an example of the annotation:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
         serving.knative.dev/progress-deadline: "45s" 
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"

```
