### ISSUE TITLE
Knative Eventing Challenge

### ISSUE THREAD

**Issue by naveengogu** [knative/docs#5792]
I am a beginner with Knative. 

1) With a broker and trigger, the event processing occurs multiple times
2) With a channel and subscription, the event is processed only once, but before completing the process the pod is terminating ( I kept sleep for 3 min in event display service).

## with brokcer and trigger

```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
    name: receiver
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver
spec:
  template:
    spec:
      containers:
        - image: 5111111111.dkr.ecr.us-east-1.amazonaws.com/knative-poc:latest1
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 5000
      timeoutSeconds: 500
---
apiVersion: sources.knative.dev/v1alpha1
kind: RedisStreamSource
metadata:
  name: receiver
spec:
  address: "rediss://redis.redis.svc.cluster.local:6379" #<redis-uri>
  stream: channel
  group: mygroup
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: receiver
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: receiver
  # namespace: ${WORKLOAD_NAMESPACE}
spec:
  broker: receiver
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: receiver

```

## with channel and subscription
```
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
metadata:
  name: channel
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver
spec:
  template:
    spec:
      containers:
        - image: 5111111111.dkr.ecr.us-east-1.amazonaws.com/knative-poc:latest2
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 5000
      timeoutSeconds: 500
---
apiVersion: sources.knative.dev/v1alpha1
kind: RedisStreamSource
metadata:
  name: receiver
spec:
  address: "rediss://redis.redis.svc.cluster.local:6379" #<redis-uri>
  stream: channel
  group: mygroup
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: channel
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription1
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: receiver

```

## my eventing service code (python)

```
from flask import Flask, request
import time
import threading
import sys

app = Flask(__name__)

# Redirect stdout and stderr to the console
sys.stdout = sys.stderr = open("/dev/stdout", "w")

def process_post_data(data):
    print(f"Received POST request with message: {data}")
    sys.stdout.flush()  # Flush the output
    # Wait for 3 minutes (180 seconds)
    time.sleep(180)
    print(f"Waited for 3 minutes: {data}")
    sys.stdout.flush()  # Flush the output

@app.route('/', methods=['GET'])
def home():
    return 'Welcome to the Dockerized API\n'

@app.route('/', methods=['POST'])
def post_handler():
    data = request.json  # Assuming JSON data in the POST request
    
    # Create a new thread to process the post data
    threading.Thread(target=process_post_data, args=(data,)).start()
    
    return 'Post message received, processing...\n'

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)

```
