### ISSUE TITLE
Issue with Documentation: Confusion Over Full Duplex Setup

### ISSUE THREAD

**Issue by QW-pawankundar** [knative/docs#5873]
There appears to be a discrepancy in the documentation regarding the configuration of full duplex support. The current documentation suggests placing the feature flag within the annotations of the service template. However, this placement does not seem to enable the desired functionality.

Documentation Reference: [Knative Documentation - Configure HTTP1 Full Duplex Support](https://knative.dev/docs/serving/services/http-protocol/#configure-http1-full-duplex-support)

Current Documentation Suggestion:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: example-service
 namespace: default
spec:
 template:
  spec:
   annotations:
    features.knative.dev/http-full-duplex: "Enabled"
```

Question:
Should the feature flag [features.knative.dev/http-full-duplex](http://features.knative.dev/http-full-duplex) be placed:

1. Inside the metadata of the service template?

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: example-service
 namespace: default
spec:
 template:
  metadata:
   annotations:
    features.knative.dev/http-full-duplex: "Enabled"
```

or 

2. directly inside the metadata?

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 annotations:
  features.knative.dev/http-full-duplex: "Enabled"
```

Any insights would be greatly appreciated. Thank you!

**Comment by ReToCode** [comment]
You are correct that this was wrong. It was fixed with https://github.com/knative/docs/pull/5867.

The current docs reflect how it should be.

**Comment by skonto** [comment]
Hi @QW-pawankundar is it ok if we close this?

**Comment by QW-pawankundar** [comment]
Sure @skonto  we can close this, we are using the below placement for the full duplex feature flag.

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: example-service
 namespace: default
spec:
 template:
  metadata:
   annotations:
    features.knative.dev/http-full-duplex: "Enabled"
```
