### ISSUE TITLE
KnativeServing CR overriding the queue-proxy registry which didn't work

### ISSUE THREAD

**Issue by xiezhao** [knative/docs#5985]
## Expected Behavior
The container queue-proxy in my pod is what i customized in KnativeServing CR 
The setting below:
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.12.3"
  registry:
    override:
      activator: docker.io/xz295139210/knative-serving-activator:1.12.3
      autoscaler: docker.io/xz295139210/knative-serving-autoscaler:1.12.3
      controller: docker.io/xz295139210/knative-serving-controller:1.12.3
      webhook: docker.io/xz295139210/knative-serving-webhook:1.12.3
      autoscaler-hpa: docker.io/xz295139210/knative-serving-autoscaler-hpa:1.12.3
      net-istio-controller/controller: docker.io/xz295139210/knative-net-istio-controller:1.12.3
      net-istio-webhook/webhook: docker.io/xz295139210/knative-net-istio-webhook:1.12.3
      queue-proxy: docker.io/xz295139210/knative-serving-queue:1.12.3
```
## Actual Behavior
every component run well except the queue-proxy
The container queue-proxy in my pod is still "gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:739d6ce20e3a4eb646d47472163eca88df59bb637cad4d1e100de07a15fe63a2"
and the value of the key "queue-sidecar-image"  in configmap "config-deployment"  is still "gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:739d6ce20e3a4eb646d47472163eca88df59bb637cad4d1e100de07a15fe63a2"

## Steps to Reproduce the Problem

1.  create the KnativeServing CR 

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): huawei cloud cce . 
 - K8s version: 1.28.4
 - Knative operator :  1.12.3
 - Knative Serving: 1.12.3
 - Isito: v1.19.7
