### ISSUE TITLE
Create OWNER-ALIASES file

### ISSUE THREAD

**Issue by samodell** [knative/docs#655]
## Context
I believe we can configure Prow to use this file to auto-assign reviewers, as in the other repos. This way, we can stop auto-assigning engineers to review docs PRs and instead auto-assign docs reviewers, who can then triage incoming PRs appropriately and assign relevant engineers as needed. Other reviewers can still be manually added.

**Comment by samodell** [comment]
@evankanderson, how do we configure Prow to use the OWNERS_ALIASES file to auto-assign folks, once that PR gets approved?

**Comment by evankanderson** [comment]
I'd assumed that you had a particular plan. Assuming you want the docs people to be put in as reviewers, but allow the eng team to also approve, try the following:

OWNERS:
```
approvers:
  - eng-approvers
  - docs-approvers
reviewers:
  - docs-approvers
```

OWNERS_ALIASES:
```
aliases:
  docs-approvers:
  - evankanderson
  - mattmoor
  - vaikas-google
  - rgregg
  - mchmarny
  - averikitsch
  docs-approvers:
  - carieshmarie
  - samodell
  - richieescarez
```
