### ISSUE TITLE
We need a sample demonstrating ConfigMap and Secrets

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#768]
The config for this ends up looking like (for secret):
```
    env:
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-for-env-test
          key: ninja
```
